1. What is NumPy?

Ans: NumPy is the Python Package. It stands for numerical Python. In data Science we use to process the array

In [1]:
# import numpy library 
import numpy

2. What is an Array?

Ans: An array is a collection of items of same data type stored at contiguous memory locations. This makes it easier to calculate the position of each element by simply adding an offset to a base

In [2]:
# saving the data in continious memory location

numpy.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [4]:
# saving the data in continious memory location * means they kept in one memory location

numpy.array([11,22,33,44,55])

array([11, 22, 33, 44, 55])

In [5]:
a=numpy.array([90,30,50,55])
a

array([90, 30, 50, 55])

In [6]:
b=numpy.array([98,54,76,38,59])
b

array([98, 54, 76, 38, 59])

In [7]:
# calling numpy by alise 

import numpy as np

In [8]:
# size will tell us number of elements 
b.size

5

In [9]:
# shape will show the dimenssion of the elements
b.shape

(5,)

In [10]:
# saving the data in one continious memory location is work of an array
b=np.array([1,2,3,4,5,6,7,8])
print("Shape or Dimension: ",b.shape) # its showing 08 elements in one side and other side is empty hence 1d
print("Size of an array : ",b.size)

Shape or Dimension:  (8,)
Size of an array :  8


## 2 DIMENSION DATA

- ( [ [ROW1], [ROW2] ] )

In [11]:
# checking the shape of c 
c=np.array([[1,2],[3,4]])

print("Shape or Dimension",c.shape) # shows 2 rows and 2 column
print("Size",c.size)

Shape or Dimension (2, 2)
Size 4


In [17]:
# checking the shape of b
b=np.array([[1,2,3,4],[2,3,4,5]])
print(type(b),"\n",b,"\n")

print("SHAPE :",b.shape)  # will show 2 rows and 4 column
print("SIZE :",b.size) # total 8 elements

<class 'numpy.ndarray'> 
 [[1 2 3 4]
 [2 3 4 5]] 

SHAPE : (2, 4)
SIZE : 8


In [20]:
# checking the shape of e
e=np.array([[3,4,5,6,'M'],[5,6,6,8,'G']])
print(e,"\n",type(e),"\n")
print("Shape",e.shape) # show two rows by 5 column
print("Size",e.size)

[['3' '4' '5' '6' 'M']
 ['5' '6' '6' '8' 'G']] 
 <class 'numpy.ndarray'> 

Shape (2, 5)
Size 10


In [21]:
# checking the shape of f
f=np.array([[4,6,7],[3,5,6],[4,6,7],[8,9,0]])
# shows 4 rows and 12 elements as size
print(f)
print("Shape ",f.shape) # shows 4 rows and 12 elements
print("Size ",e.shape)

[[4 6 7]
 [3 5 6]
 [4 6 7]
 [8 9 0]]
Shape  (4, 3)
Size  (2, 5)


In [22]:
# checking the shape,size of g

g=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]]) # 5 rows and 2 columns and size is 10

# print 
print(g)
print(g.shape)
print(g.size)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)
10


In [23]:
# checking the shape, dimension and size of h

h=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(h)

# will show the shape as 3 rows and 3 column
print(h.shape)

# will show the total elements inside it
print(h.size)

# ndim will show the dimension 
print(h.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
2


In [27]:
i=np.array([[2,2,3,3],[4,4,4,4],[5,5,5,5]]) # will show the shape as 3 rows and 4 column
print(i)

# will show the shape as 3 rows and 4 columns
print("Shape :",i.shape)

# will show the size as 12 as total elements are 12
print("SIZE :",i.size)

# will show the dimension 
print("Dimension :",i.ndim)

# will show the minimum and maximum from in an array

print("Max : ",i.max())
print("Min : ",i.min())

# will show the data type 
print("Data Type :",i.dtype)

[[2 2 3 3]
 [4 4 4 4]
 [5 5 5 5]]
Shape : (3, 4)
SIZE : 12
Dimension : 2
Max :  5
Min :  2
Data Type : int32


## Re-shape

In [29]:
f=i.reshape(4,3)
f

array([[2, 2, 3],
       [3, 4, 4],
       [4, 4, 5],
       [5, 5, 5]])

## Dtype

In [31]:
# 32 is bytes memory consumed
f.dtype

dtype('int32')

In [30]:
# 4 bytes is consumed by each item
f.itemsize

4

In [32]:
a=np.array([[1,2],[3,4],[5,6]])

print("Shows 3 rows and 2 columns ",a.shape)
print("Shows dimension as ",a.ndim)
print("Data Type",a.dtype)
print("Shows memory consumed by elements as ",a.itemsize)
print("Will Show the Minimum from Array ",a.min())
print("Will Show the Maximum from Array",a.max())
print("Changing The shape of a\n\n",a.reshape(2,3))

Shows 3 rows and 2 columns  (3, 2)
Shows dimension as  2
Data Type int32
Shows memory consumed by elements as  4
Will Show the Minimum from Array  1
Will Show the Maximum from Array 6
Changing The shape of a

 [[1 2 3]
 [4 5 6]]


# Aranage function

In [35]:
x=np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
a=x.reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [38]:
n=np.arange(15,dtype='float64')
n.reshape(3,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [40]:
print("SHAPE" ,a.shape)
print("Size",a.size)
print("Dimension",a.dtype)
print("Type",type(a))
print("Max",a.max())
print("Min",a.min())
print("Item SIZE per element",a.itemsize)

SHAPE (4, 3)
Size 12
Dimension int32
Type <class 'numpy.ndarray'>
Max 11
Min 0
Item SIZE per element 4


## Consumtion

- 8 bit is 1 byte
- 32 byte/8 byte is 4byte 

In [41]:
c=np.arange(15,dtype='float64')
f=n.reshape(3,5)
print(f.dtype)

# gives the number of bytes: it is float64 data type hence it takes 8 byte to store the data
print(f.itemsize)

float64
8


## Consumtion

- 8 bit == 1 byte
- 64 byte/8 byte is 8 byte

In [43]:
a=np.array([1,2,3,4])

# show 1 dimensions
a.ndim

1

In [44]:
f=a.reshape(2,2)
f.ndim

2

In [45]:
print(f)

[[1 2]
 [3 4]]


In [48]:
f=np.arange(12).reshape(4,3)
print("Will reshape the numbers into 4 rows and 3 column")
print(f,"\n\n")
print("SHAPE :",f.shape,"\nSIZE :",f.size,"\nDimension :",f.ndim,"\nMAX :",f.max(),"\nMIN :",f.min(),"\nRESHAPE into 6 ROWS and 2 COLUMNS\n",f.reshape(6,2))

Will reshape the numbers into 4 rows and 3 column
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 


SHAPE : (4, 3) 
SIZE : 12 
Dimension : 2 
MAX : 11 
MIN : 0 
RESHAPE into 6 ROWS and 2 COLUMNS
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [49]:
print("TYPE :",type(f))
print("DATA TYPE :",f.dtype)
print("ITEM SIZE :",f.itemsize)

TYPE : <class 'numpy.ndarray'>
DATA TYPE : int32
ITEM SIZE : 4


# RAVEL FUNCTION

In [54]:
# it will change the 2D data to 1D data

b=np.arange(16).reshape(4,4) # will reshape the data to 2D
print(b)
print("SHAPE ",b.shape)
print("Size",b.size)
print("Dimension ",b.ndim)

c=b.ravel()
print("\n\nAfter using Ravel Function \n",c) 
print("SHAPE ",c.shape)
print("Size",c.size)
print("Dimension",c.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
SHAPE  (4, 4)
Size 16
Dimension  2


After using Ravel Function 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
SHAPE  (16,)
Size 16
Dimension 1


In [55]:
b=np.array([[1,2,3],[3,5,4]])
print(b)
print(b.shape)
print(b.size)

[[1 2 3]
 [3 5 4]]
(2, 3)
6


# Numpy Zeros/ Ones

In [60]:
f=np.zeros([4,4])
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
f=np.ones([4,4])
f

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Arange function

In [62]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# will generate 10 numbers except last 
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# will generate 10 numbers except last
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# Broadcasting Numpy

The term broadcasting describes how numpy treats arrays with different shapes during arthematic operations. Subject to certain contrainsts, the smaller array is broadcast across the larger array so that they have compatible shapes. broadcasting provides a means of vectorizing array operations

In [74]:
a=np.arange(1,4)
b=np.array([2,2,2])

print(a*b)

[2 4 6]


In [75]:
a=np.array([1,2,3],dtype='float64')
print(a)

b=np.array([2,2,2],dtype='float64')
print(b)

a*b

[1. 2. 3.]
[2. 2. 2.]


array([2., 4., 6.])

In [76]:
a=np.array([20,30,40,50])
b=np.array([2],dtype='float64')
print(a)
print(b)
print(a*b)

[20 30 40 50]
[2.]
[ 40.  60.  80. 100.]


In [78]:
a=np.array([1,2,3,4])
b=np.arange(1,5,1)
print(a)
print(b)

print("SUM :",a+b)

[1 2 3 4]
[1 2 3 4]
SUM : [2 4 6 8]


In [79]:
print(a-b)

[0 0 0 0]


In [84]:
# will genrate all random number

b=np.random.random([2,3])
b

array([[0.03007113, 0.63083033, 0.17820898],
       [0.99944661, 0.65107451, 0.55246795]])

In [85]:
c=np.ones([2,3])

b+c

array([[1.03007113, 1.63083033, 1.17820898],
       [1.99944661, 1.65107451, 1.55246795]])

In [99]:
print("SUM\n",b+c)
print("\nSUBS\n",c-b)
print("\nMULTIFY\n",c*b)

SUM
 [[1.03007113 2.63083033 3.17820898]
 [1.99944661 2.65107451 3.55246795]]

SUBS
 [[9.69928873e-01 1.36916967e+00 2.82179102e+00]
 [5.53394925e-04 1.34892549e+00 2.44753205e+00]]

MULTIFY
 [[0.03007113 1.26166066 0.53462695]
 [0.99944661 1.30214901 1.65740386]]


# Universal Function

In [88]:
B=np.arange(3)
B

array([0, 1, 2])

In [89]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [90]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [91]:
c=np.array([1,2,3])
np.add(B,c)

array([1, 3, 5])

In [92]:
np.subtract(B,c)

array([-1, -1, -1])

## Indexing/ Slicing

In [93]:
f=np.arange(10)
print(f)
print(f[2:5])
print(f[:5])
print(f[-1])
print(f[-3:-1])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 1 2 3 4]
9
[7 8]


### NOTE :

- For Missing value  we use {np.nan}

In [95]:
d1=np.array([[1,np.nan,3],[4,np.nan,5]])
d1

array([[ 1., nan,  3.],
       [ 4., nan,  5.]])

# Rand Function

In [97]:
# will generate only positive numbers
np.random.rand(4,4)

array([[0.96074151, 0.93134394, 0.3717247 , 0.97174196],
       [0.90929474, 0.44336226, 0.79978327, 0.77137776],
       [0.93278569, 0.29338586, 0.86312414, 0.03744978],
       [0.88015017, 0.94495173, 0.05753798, 0.07942272]])

# Randn Function

In [98]:
# will generate negative and positive number
np.random.randn(4,5)

array([[-0.52941771, -0.13647639,  0.05245058, -1.20533735, -0.2698697 ],
       [ 0.28936241, -1.2424707 ,  0.30038599,  0.42411881,  0.44125465],
       [-0.58610356,  0.68716095,  0.52838447, -0.81454249,  0.86744024],
       [-0.41681855, -0.54348159, -0.95052065, -0.27212357,  0.6029774 ]])

"NOTE"

- We use Randn function to genrate any number for normal distribution in thr given dimenssion format

____________________

------------------

........................................    **LMS MODULE**    ..............................................

## Numpy Array

### Array: 

An array is a collection of items of same data type stored at contiguous memory locations

In [1]:
import numpy as np

In [2]:
np.array([list])

array([<class 'list'>], dtype=object)

In [3]:
## Changing dtype

a=np.array([[1,2,3],[3,3,3]],dtype='float')
print(a)
a.dtype

[[1. 2. 3.]
 [3. 3. 3.]]


dtype('float64')

In [6]:
## create matrix

a=np.array(np.mat('1 2 3;1 2 3')) # columns of row1 and row2 has to hold same number of data, else it would throw error
a                  

array([[1, 2, 3],
       [1, 2, 3]])

In [7]:
# convert a list into array

a=[1,2,3]

b=np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
# making a copy of an array

c=np.asarray(b)

c

array([1, 2, 3])

## Numpy Dtypes

In [11]:
my_mat=np.array(np.mat('1 2 3;4 5 6;7 8 9')) # np.nan can't be used in string format

# printing array named my_mat
print(my_mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print("Type/Class of the Matrix ",type(my_mat)) # will show the class of the object
print("Dimenssion ",my_mat.ndim) # will show the dimension of the matrix
print("Shape ",my_mat.shape) # shows 3 rows and 3 columns
print("Size ",my_mat.size) #  shows the total number of elements
print("Data Type ",my_mat.dtype) # shows the data type of the inserted data like float, int
print("Memory consumed by Each element ",my_mat.itemsize) # shows the memory consumed by each element

Type/Class of the Matrix  <class 'numpy.ndarray'>
Dimenssion  2
Shape  (3, 3)
Size  9
Data Type  int32
Memory consumed by Each element  4


## Numpy Arange and linespace

In Python we have range where we have start/stop/ Jump, We have the same thing as (A...range function) in Numpy

In [14]:
list(range(0,5)) # will show the data till 0 to 4 element

[0, 1, 2, 3, 4]

In [15]:
# But Range function won't work if those data is provided in float: example

list(range(0,5,0.4))

TypeError: 'float' object cannot be interpreted as an integer

- However we see that float doesn't work with range function, Hence we would use arange function which is in numPy

In [19]:
# example 2

print(np.arange(0,5,0.4))

[0.  0.4 0.8 1.2 1.6 2.  2.4 2.8 3.2 3.6 4.  4.4 4.8]


In [21]:
# example 3
a=np.arange(0,5.5,0.4)
print(a)

[0.  0.4 0.8 1.2 1.6 2.  2.4 2.8 3.2 3.6 4.  4.4 4.8 5.2]


## Reverse Order

In [23]:
# Reverse Order [start/end/-1(means backword direction)]

print(a[::-1]) # all reversed

[5.2 4.8 4.4 4.  3.6 3.2 2.8 2.4 2.  1.6 1.2 0.8 0.4 0. ]


In [30]:
a[2::-1] # start from index 2 in back word direction

array([0.8, 0.4, 0. ])

#### NOTE:
    
    To generate reverse number the start point should be high and end point to be low

In [31]:
# will generate the data from 50 to 5 as 0 is the last element

np.arange(50,0,-5)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [32]:
# will not generate the data as 0 can be but to minus but reching positive 50 won't be possible hence its empty

np.arange(0,50,-5)

array([], dtype=int32)

## "Linearly spaced"

In [33]:
print("Printing spaced numbers between 1 to 5 \n---------------------------------")
print(np.linspace(10,40,5)) # create 5 numbers with equal space (linspace means Linnearly spaced) 

Printing spaced numbers between 1 to 5 
---------------------------------
[10.  17.5 25.  32.5 40. ]


In [34]:
# include end point and check space between the points
print(np.linspace(2.0,3.0, num=4, endpoint=True, retstep=True))

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)


#### NOTE:

- endpoint is true means will show end point 
- retstep will show the space/stepsize taken 

## Matrix creation

we can't create the Series of zeroes and Ones with the help of linspace, range or arange function. We use np.zeros to create zeros

In [36]:
print("Vector of zeroes\n---------------------------------")
print(np.zeros(5))

Vector of zeroes
---------------------------------
[0. 0. 0. 0. 0.]


In [37]:
# generate the matrix of matrix

print(np.zeros((5,6))) # 5 rows and 6 column

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [39]:
# Matrix of ones in 1 Dimension

print("Matrix of ones \n....................................")
a=np.ones(5)
print(a)
print("\nType: ",type(a))
print("Dimension: ",a.ndim)
print("Size: ",a.size)
print("Shape: ",a.shape)


Matrix of ones 
....................................
[1. 1. 1. 1. 1.]

Type:  <class 'numpy.ndarray'>
Dimension:  1
Size:  5
Shape:  (5,)


In [42]:
# Matrix of ones in 2 Dimension

print("Matrix of Ones In 2 Dimensions\n...........................")
a=np.ones((5,6))
print(a)
print("\nType: ",type(a))
print("Dimension: ",a.ndim)
print("Size: ",a.size)
print("Shape: ",a.shape)

Matrix of Ones In 2 Dimensions
...........................
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

Type:  <class 'numpy.ndarray'>
Dimension:  2
Size:  30
Shape:  (5, 6)


In [46]:
# print Matrix of 5 by using ones

print("Matrix of 5 by using ones\n...................................")
a=5*np.ones((4,5)) # 4 rows and 5 columns
print(a)

print("\ntype: ",type(a))
print("Dimension: ",a.ndim)
print("Shape: ",a.shape)
print("Size: ",a.size)
print("Data Type: ",a.dtype)
print("Memory Consumed by each element: ",a.itemsize)
print("Max: ",a.max())
print("Min: ",a.min())
print("Reshape The structure in Matrix of (2 rows and 10)\n............................................\n",a.reshape(2,10))

Matrix of 5 by using ones
...................................
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]

type:  <class 'numpy.ndarray'>
Dimension:  2
Shape:  (4, 5)
Size:  20
Data Type:  float64
Memory Consumed by each element:  8
Max:  5.0
Min:  5.0
Reshape The structure in Matrix of (2 rows and 10)
............................................
 [[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


## Contruct Diagonal matrix

In [47]:
# arange can generate float elements starts from 0 till minus 1 to end point
x=np.arange(30).reshape(5,6) # reshape to 5 rows and 6 columns
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


## Random Number Generation

**Are of 3 type**

- np.random.rand : Rand would generate Uniform distribution data **Uniform Distribution**
- np.random.randn :  Would genrate the numbers postive and negative **Normal Distribution**
- np.random.randint : 

np.random.seed(5) # any number has its own randomness and will generate number 

*IF we don't use seeding it would be hard to trace the generated number *

In [52]:
print("Random will generate random data and rand Would generate the **Uniform distribution** of data\n","-"*80)

print(np.random.rand(10,6))

Random will generate random data and rand Would generate the **Uniform distribution** of data
 --------------------------------------------------------------------------------
[[0.57537152 0.56699862 0.70021516 0.83212093 0.22891763 0.09535153]
 [0.11660445 0.20099284 0.02104168 0.00975941 0.15585286 0.60178002]
 [0.81663441 0.23866921 0.28713188 0.13902332 0.07148019 0.74789165]
 [0.42102393 0.49943975 0.48659862 0.53493703 0.32995791 0.59035303]
 [0.0671327  0.44712007 0.42718094 0.64154528 0.3731534  0.07922459]
 [0.36033525 0.85158885 0.20381484 0.00335507 0.17987386 0.57994032]
 [0.23607149 0.93523925 0.95760887 0.01182194 0.34200061 0.55247062]
 [0.59355384 0.781037   0.60330914 0.61892765 0.53886157 0.51064042]
 [0.69933214 0.74526671 0.6510183  0.30302368 0.9165439  0.55450849]
 [0.53501219 0.43163305 0.89054006 0.92280741 0.20020714 0.44846104]]


In [57]:
print("Random number will be generated numbers which has ** NORMAL DISTRIBUTION with zero mean and std=1 **\n",'-'*100)
print(np.random.randn(5,6)) # 5 rows and 6 columns

Random number will be generated numbers which has ** NORMAL DISTRIBUTION with zero mean and std=1 **
 ----------------------------------------------------------------------------------------------------
[[-1.4047922  -0.50299628 -0.11989347  0.64098353 -1.29913799 -0.67949243]
 [ 0.39122107 -0.73064677 -0.77159447 -0.06141736  2.59573155  1.68768329]
 [-0.23582115  1.95465498  0.85795372  0.9568722  -1.40003821  0.46281667]
 [ 0.31816145  1.43263667  0.84457053  1.48774987  1.6763097   1.25375055]
 [ 1.29617147 -0.83825857 -0.22754969 -1.70496983 -0.52219719  1.46831541]]


In [60]:
# RANDINT has to pick number from start, till stop, and number of elements to be drawn

print("Random Integer Vector\n\n",np.random.randint(5,20,10)) # pick up 10 numbers from 5 to 20 can be same number as its picked randomly

Random Integer Vector

 [ 6 18 16  9 17  9 15 17 10 11]


- NOTE: 10 is the size

In [64]:
# Randint
print("print random  Integer Matrix")
print(np.random.randint(5,20,size=(5,6))) # here 5 start,20 end and matrix of (5 rows and 6 columns)

print random  Integer Matrix
[[14 18  5  7  8  9]
 [ 7 19  5 15  7 19]
 [ 6 18 19  7 10 15]
 [15  6 14 16 16 17]
 [12  8 13 18 17  7]]


## Numpy Condition

In [66]:
# random integer
a=np.random.randint(1,40,10)
a

array([ 1, 29, 27, 18, 31,  3, 31,  5, 36, 26])

In [67]:
# generate 10 numbers between 1 to 30

b=np.random.randint(1,30,10)
print(b)

[20  1  5  9 14  9 13 19 18 29]


## np.clip

1. np.clip: replace data with fixed number

In [70]:
# replace data with fixed numbers 

np.clip(b, a_min=10, a_max=20) # will make data less than 10 to 10 and max will make data above 20 as 20

array([20, 10, 10, 10, 14, 10, 13, 19, 18, 20])

In [71]:
# replace data below 9 as 9 and more than 15 as 15

np.clip(b,a_max=15,a_min=9)

array([15,  9,  9,  9, 14,  9, 13, 15, 15, 15])

In [74]:
# checking the index position  where b is less than 10

np.where(b<10) # checking where b is less than 10

(array([1, 2, 3, 5], dtype=int64),)

In [75]:
# checking the index position where b is more than 10

np.where(b>10)

(array([0, 4, 6, 7, 8, 9], dtype=int64),)

In [77]:
# checking the postion where b is greater then or equals to 20

np.where(b>=20)

(array([0, 9], dtype=int64),)

# RE-Shape

In [78]:
# creating instance 

import numpy as np

# importing randint from numpy.random 
from numpy.random import randint as ri

In [85]:
a=ri(5,99,30)
print("Calling 10 random integers by using randint\n-------------------------------------\n",a)

Calling 10 random integers by using randint
-------------------------------------
 [97 71 77 59 34 69 24 34 87 47 23 47 98  7 80 96 32 37 73 65 64 22 32 45
 12 39 65 73 97 27]


## Create Two Matrix

In [86]:
# Note 30 numbers are generated from randint function.. and we made 2 matrix of each of 15 elements {3*5=15}

b=a.reshape(2,3,5) # here 2 is TWO MATRIX,3 rows and 5 as columns,

b

array([[[97, 71, 77, 59, 34],
        [69, 24, 34, 87, 47],
        [23, 47, 98,  7, 80]],

       [[96, 32, 37, 73, 65],
        [64, 22, 32, 45, 12],
        [39, 65, 73, 97, 27]]])

In [87]:
# creating single matrix

c=a.reshape(5,6)
c

array([[97, 71, 77, 59, 34, 69],
       [24, 34, 87, 47, 23, 47],
       [98,  7, 80, 96, 32, 37],
       [73, 65, 64, 22, 32, 45],
       [12, 39, 65, 73, 97, 27]])

## Find Minimum/ Maximum

In [88]:
print("Min in C: ",c.min())
print("Maximum in C: ",c.max())

Min in C:  7
Maximum in C:  98


In [89]:
print("Min in b: ",b.min())
print("maximum in b",b.max())

Min in b:  7
maximum in b 98


## Sorting in Numpy

In [4]:
f=np.random.randint(1,50,25).reshape(5,5)
print(f)

[[25 46 26  8 14]
 [45 40 49 25 27]
 [33 20 46 25 21]
 [42 35 41 22 43]
 [38 42  7 22 23]]


In [5]:
# will sort in ascending order and in each row

print("DATA IS IN ASCENDING ORDER ROW WISE when axis is -1\n---------------------------------")
g=np.sort(f,axis=-1) # axis is -1 
g

DATA IS IN ASCENDING ORDER ROW WISE when axis is -1
---------------------------------


array([[ 8, 14, 25, 26, 46],
       [25, 27, 40, 45, 49],
       [20, 21, 25, 33, 46],
       [22, 35, 41, 42, 43],
       [ 7, 22, 23, 38, 42]])

In [6]:
# data will be in ascending in column wise

h=np.sort(f,axis=0)
print("SORT DATA in ACENDING order column Wise\n------------------------------------")
print(h)

SORT DATA in ACENDING order column Wise
------------------------------------
[[25 20  7  8 14]
 [33 35 26 22 21]
 [38 40 41 22 23]
 [42 42 46 25 27]
 [45 46 49 25 43]]


## Indexing and slicing

In [95]:
arr=np.arange(12,30)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [97]:
print("Element at the 7th index: ",arr[7])
print("Element at the 3rd and 4th index: ",arr[3:5])
print("Element from 4th index till end: ",arr[4:])
print("Element from backwards are escaping one one element: ",arr[-1::-2])

Element at the 7th index:  19
Element at the 3rd and 4th index:  [15 16]
Element from 4th index till end:  [16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Element from backwards are escaping one one element:  [29 27 25 23 21 19 17 15 13]


In [98]:
print("7 elements from backwards are: ",arr[-1:-8:-1])
print("Element in 7th 4th and 9th index are: ",arr[[7,4,9]]) # pass the index number in list

7 elements from backwards are:  [29 28 27 26 25 24 23]
Element in 7th 4th and 9th index are:  [19 16 21]


In [99]:
arr=np.arange(0,21,2) # step size 2
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [100]:
print("Element from 4th 7th 9th : ",arr[[4,7,9]]) # pass the index number in list to get random particular number

Element from 4th 7th 9th :  [ 8 14 18]


In [101]:
len(arr)

11

In [104]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

mat=np.array(my_matrix)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Double bracket indexing

In [107]:
print("Double bracket indexing\n-----------------\n","Element in row 1 and column index 2 is:  ",mat[1][2]) 

# will check for row 1 and row 0  will be ignored and will look for 2nd element in row 1 that is 6

Double bracket indexing
-----------------
 Element in row 1 and column index 2 is:   6


In [113]:
print("Elements in row 2: ",mat[2]) # first is rows
print("Elements in row 1: ",mat[1]) # first is rows
print("Elements in row 0: ",mat[0]) # first is rows
print("element in row 0 and column: ",mat[0][1:]) # row 0 and all element from index 1 to index end

Elements in row 2:  [7 8 9]
Elements in row 1:  [4 5 6]
Elements in row 0:  [1 2 3]
element in row 0 and column:  [2 3]


In [114]:
print("Entire column at index 3: \n",mat[:,1:])

Entire column at index 3: 
 [[2 3]
 [5 6]
 [8 9]]


In [117]:
print("Subsetting sub Matrices\n''''''''''''''''''''''''''''''''''''''''''''''''''''''''\n")
print('Entire column at index 3\n',mat[:,1:])# left {empty} is rows and right is column

Subsetting sub Matrices
''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Entire column at index 3
 [[2 3]
 [5 6]
 [8 9]]


In [118]:
# row 1 to row 2(here row 2 is excluded) and column 1 and 2 will be exculded

print("Matrix with row 1 and column 1 and row 2 and column 2 will be excluded....",mat[1:2,1:2])

Matrix with row 1 and column 1 and row 2 and column 2 will be excluded.... [[5]]


In [119]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [120]:
mat[2:,[0,1,2]]

array([[7, 8, 9]])

In [122]:
mat[0:2,0:2]

array([[1, 2],
       [4, 5]])

## Update Matrix

In [123]:
print('Original Matrix\n-----------------------\n',mat)

Original Matrix
-----------------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [128]:
print("updated Matrix\n******************************\n")# zeroth row and first column is 35
mat[0,1]=35

print("After update")
print(mat)

updated Matrix
******************************

After update
[[ 1 35  3]
 [ 4  5  6]
 [ 7  8  9]]


## Subsetting

In [3]:
import numpy as np
from numpy.random import randint as ri

mat=np.array(ri(0,100,15)).reshape(3,5)
print("Matrix of 2 digit number\n---------------------------\n")
print(mat)

Matrix of 2 digit number
---------------------------

[[55 77 12 80 86]
 [25 64 42 15 29]
 [44 27 83 88 83]]


In [7]:
# checking where matrix element is greater than 70
mat[mat>70]

array([77, 80, 86, 83, 88, 83])

- result shows which elements are greater than 70

In [8]:
# this will show where its more than 50

mat>50

array([[ True,  True, False,  True,  True],
       [False,  True, False, False, False],
       [False, False,  True,  True,  True]])

In [9]:
print(np.where(mat==88)) # 2nd row and 3rd column

(array([2], dtype=int64), array([3], dtype=int64))


In [10]:
mat

array([[55, 77, 12, 80, 86],
       [25, 64, 42, 15, 29],
       [44, 27, 83, 88, 83]])

## Universal Function

In [25]:
mat1=np.arange(0,16).reshape(4,4)
print("First Matrix One:\n-----------------------------------\n",mat1)

mat2=np.array(ri(0,100,(4,4)))
print("\n Second Matrix:\n------------------------------------\n",mat2)

mat3=np.array(ri(0,20,16)).reshape(4,4)
print("\nThird Matrix\n---------------------------------------\n",mat3)

First Matrix One:
-----------------------------------
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 Second Matrix:
------------------------------------
 [[98 79 73 65]
 [57 98 49 66]
 [28 24 73 14]
 [ 2 45 74 94]]

Third Matrix
---------------------------------------
 [[16  5  2 18]
 [14  3  2  4]
 [ 5 13  3  4]
 [18  6 14  0]]


In [27]:
print("Addition\n-----------------------\n",np.add(mat1,mat2))
print("Substraction\n--------------------\n",np.subtract(mat1,mat2))
print("Multiplication\n-------------------\n",np.multiply(mat1,mat3))

Addition
-----------------------
 [[ 98  80  75  68]
 [ 61 103  55  73]
 [ 36  33  83  25]
 [ 14  58  88 109]]
Substraction
--------------------
 [[-98 -78 -71 -62]
 [-53 -93 -43 -59]
 [-20 -15 -63  -3]
 [ 10 -32 -60 -79]]
Multiplication
-------------------
 [[  0   5   4  54]
 [ 56  15  12  28]
 [ 40 117  30  44]
 [216  78 196   0]]


In [31]:
print("Division\n--------------------------\n",np.divide(mat1,mat3))
print("Add\n------------------------------\n",2*mat1)
print("Subtract\n-------------------------\n",3-mat1)

Division
--------------------------
 [[0.         0.2        1.         0.16666667]
 [0.28571429 1.66666667 3.         1.75      ]
 [1.6        0.69230769 3.33333333 2.75      ]
 [0.66666667 2.16666667 1.                inf]]
Add
------------------------------
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]
Subtract
-------------------------
 [[  3   2   1   0]
 [ -1  -2  -3  -4]
 [ -5  -6  -7  -8]
 [ -9 -10 -11 -12]]


C:\Users\jitsa\AppData\Local\Temp\ipykernel_11556\239181869.py:1: RuntimeWarning: divide by zero encountered in true_divide
  print("Division\n--------------------------\n",np.divide(mat1,mat3))


In [34]:
print((5*mat1-2*mat3+mat1)/5*mat1)

[[ -0.   -0.8   3.2 -10.8]
 [ -3.2  24.   38.4  47.6]
 [ 60.8  50.4 108.  127.6]
 [ 86.4 171.6 156.8 270. ]]


In [38]:
print("Mat1\n------------------------------\n",mat1)
print("\nMultiplication on matrix\n----------------------------\n",3*mat1)

Mat1
------------------------------
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Multiplication on matrix
----------------------------
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]
 [36 39 42 45]]


## Broadcasting

- Lets understand how it works in different different matrix

In [64]:
start=np.zeros((4,4))
print("Matrix 'START'\n-----------------\n",start)

Matrix 'START'
-----------------
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [57]:
row=np.array(ri(0,10,4)).reshape(1,4)
print(row)
print(row.ndim)

[[6 3 2 1]]
2


In [58]:
add_row=np.array([1,2,3,4])
print(add_row)
print(add_row.ndim)

[1 2 3 4]
1


In [65]:
# adding row wise

f=row+start
g=add_row+start
print("Added row Wise\n--------------------\n",f,"\n\n",g)

Added row Wise
--------------------
 [[6. 3. 2. 1.]
 [6. 3. 2. 1.]
 [6. 3. 2. 1.]
 [6. 3. 2. 1.]] 

 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


## Transpose

- Rows can be changed in columns and columns can be changed into rows

In [66]:
# here row is in 2 dimension so can be tranposed
column=row.T
print(column)

add_column=add_row.T # here add_row is in one dimension so can't be transposed
print(add_column)

[[6]
 [3]
 [2]
 [1]]
[1 2 3 4]


In [69]:
print("Addition  on  column Wise\n-----------------------------\n")
print(column+start)

Addition  on  column Wise
-----------------------------

[[6. 6. 6. 6.]
 [3. 3. 3. 3.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


## Array Maths

In [71]:
# generate random integer with randint

F_number=np.array(ri(0,10,9)).reshape(3,3)
print("First- Number\n---------------\n",F_number)

S_number=np.arange(0,9).reshape(3,3)
print('\nSecond Number\n----------------\n',S_number)

First- Number
---------------
 [[6 6 9]
 [0 6 5]
 [2 9 7]]

Second Number
----------------
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [72]:
# finding square root of first number
np.sqrt(F_number)

array([[2.44948974, 2.44948974, 3.        ],
       [0.        , 2.44948974, 2.23606798],
       [1.41421356, 3.        , 2.64575131]])

In [73]:
# finding square of first number
np.square(F_number)

array([[36, 36, 81],
       [ 0, 36, 25],
       [ 4, 81, 49]], dtype=int32)

In [75]:
# Similarly we apply all these functions 

In [76]:
import numpy as np
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

-----------------------------------------